name: PR Source Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout head ref of repository (PR)
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: ${{github.event.pull_request.head.repo.full_name}}
        ref: ${{github.event.pull_request.head.ref}}
        fetch-depth: 0

    - name: Run validation with Docker image on PR
      run: docker run --rm -v $(pwd):/opt/docker-mei/music-encoding ghcr.io/music-encoding/docker-mei:latest ant validate-source -noinput -buildfile music-encoding/build.xml
